spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ng-billing?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8080